- email/templates/confirm-quote-driver.html
added pickup date time to confirm quote driver template
> added pickup date time to confirm quote driver template

- email/templates/cancel-offer-driver.html
- email/templates/confirm-quote-driver.html
- email/templates/confirm-quote-owner.html
- email/templates/delivered.html
- email/templates/driver-nearby-dropoff.html
- email/templates/driver-nearby-pickup.html
- email/templates/edit-job-driver.html
- email/templates/load-pickedup-owner.html
- email/templates/new-job-posted.html
- email/templates/new_message_recieved.html
- email/templates/payment-escrow-owner.html
- email/templates/payment-released-driver.html
- email/templates/payment-released-owner.html
- email/templates/submit-quote-owner.html
added unsubscription link. 
Needs to have rulesservice :: email-unsubscription branch merged with master, before layouts can be merged into master.
> added unsubscription link

- email/templates/no-quotes-owner.html
new template no no-quotes-on-new-load
> new template no no-quotes-on-new-load

- email/templates/delivered.html
- email/templates/load-pickedup-owner.html
Requires qwanda-utils : generic-mergeutil branch merged in master.
> email templates to support generic mergeutil - generic merge for dates

- email/templates/delivered.html
- email/templates/load-pickedup-owner.html
using java DateFormatter formats instead of custom stuff
> merge for dateformat

- pcss-new/sublayouts/sidebar/sidebar.card.json
- pcss-new/sublayouts/sidebar/sidebar.dropdown.json
added test id for the sidebar items
> added testid to the sidebar items

- internmatch-new/pages/active-internships-table/index.json
- internmatch-new/pages/completed-internships-table/index.json
- internmatch-new/pages/contacts-table/index.json
- internmatch-new/pages/inprogress-internships-table/index.json
- internmatch-new/pages/internships-table/index.json
- internmatch-new/pages/internships/index.json
- internmatch-new/pages/offered-internships-table/index.json
- internmatch-new/pages/placed-internships-table/index.json
- internmatch-new/routing.dev.json
- internmatch-new/sublayouts/header/header.default.json
- internmatch-new/sublayouts/home/agent/bucket.json
- internmatch-new/sublayouts/home/agent/internship-details.json
- internmatch-new/sublayouts/home/intern/bucket.json
- internmatch-new/sublayouts/home/intern/index.json
- internmatch-new/sublayouts/home/intern/map-view.json
- internmatch-new/sublayouts/notes/index.json
- internmatch-new/sublayouts/sidebar-right/sidebar-right.default.json
- internmatch-new/sublayouts/sidebar/sidebar.default.json
- internmatch-new/sublayouts/tables/contacts/table-contacts.json
- internmatch-new/sublayouts/tables/internships/table-internships-active.json
- internmatch-new/sublayouts/tables/internships/table-internships-completed.json
- internmatch-new/sublayouts/tables/internships/table-internships-inprogress.json
- internmatch-new/sublayouts/tables/internships/table-internships-offered.json
- internmatch-new/sublayouts/tables/internships/table-internships-placed.json
- internmatch-new/sublayouts/tabs/tabs-default.json
updating internmatch tables and mobile responsiveness
> Internmatch mobile responsiveness

- internmatch-new/pages/companies/agencies/index.json
- internmatch-new/pages/companies/education-providers/index.json
- internmatch-new/pages/companies/host-companies/index.json
- internmatch-new/pages/contacts/agents/index.json
- internmatch-new/pages/contacts/education-provider-reps/index.json
- internmatch-new/pages/contacts/host-company-reps/index.json
- internmatch-new/pages/contacts/interns/index.json
- internmatch-new/sublayouts/view-details/company.json
- internmatch-new/sublayouts/view-details/contact.json
Sublayout code is incorrect for detail views.
1) Click on `Contacts/Interns` from sidebar.
2) Click on `Detail View`. Should see Profile page.
3) Repeat for:
3a) `Contacts/Agents`
3b) `Contacts/Edu Provider Reps`
3c) `Contacts/Host Company Reps`
3d) `Contacts/Host Companies`
3e) `Contacts/Agencies`
3f) `Contacts/Edu Provider`
> Hotfix intm 289

- internmatch-new/sublayouts/header/header.default.json
Added testid on the top right corner dropdown. Tested locally and it's working.
> Added testid on dropdown

- pcss-new/pages/identified/index.json
- pcss-new/pages/view-property/:id/index.json
- pcss-new/sublayouts/form/index.json
- pcss-new/sublayouts/header/header.default.json
- pcss-new/sublayouts/home/properties/bucket-view/bucket.json
- pcss-new/sublayouts/home/properties/bucket-view/bucketOld.json
- pcss-new/sublayouts/home/properties/table-view.json
- pcss-new/sublayouts/notes/index.json
Changes done in this pull request : 
1) fixed notes to send the appropriate itemcode for BEG or APP selection
2) Fixed traffic lights
3) Removed "country name" from the APP card in the process-view
4) Fixed button code that was being sent for BEG-delete-icon click.
> Pcs 90 part3

- mentormatch-new/pages/registration/role/index.json
Non-breaking change, just adding in testID.
> Added testid for roleselect buttons

- internmatch-new/pages/application/:id/offer/:university/agreement/:offerId/index.json
1. internship agreement document layout change made it more presentable.
> Hotpatch 2

- pcss-new/sublayouts/home/properties/bucket-view/bucket.json
- pcss-new/sublayouts/home/properties/index.json
Change bucket-view look, added legends for every bucket
1. Go to PCSS.
2. Select a property in the table-view and goto "Process View"
3. You should see legends in every bucket with status colour mapping
4. The spacing between buckets lessened, the colour of spacing between tabs changed
> Pcs 90 part4

- internmatch-new/sublayouts/home/agent/bucket.json
added host company name to the education provider role in the bucket view card 
login as edu provider and then go to the bucket then you should be able to see the name of host company
> addded host company name on the edu provider card

- internmatch-new/document_templates/AggrementPlan-CQU.html
- internmatch-new/document_templates/AggrementPlan-Revised.html
Task : INTM-885
Description: Updated Internship Agreement for CQU and added Scope to the default outcome Aggrement.
How to Test:
1) Generate the induction document by offering internship to interns.
> Change to aggrement doc template

- internmatch-new/sublayouts/home/agent/bucket.json
Moved the delete button downward.
> Delete int btn 

- internmatch-new/document_templates/AggrementPlan-CQU.html
> fixed css on CQU agreement

- internmatch-new/sublayouts/home/intern/bucket.json
> fix for bucket

- internmatch-new/routing.dev.json
- internmatch-new/sublayouts/home/agent/index.json
- internmatch-new/sublayouts/home/dashboard/stats.interns.json
- internmatch-new/sublayouts/home/edu-provider/index.json
Rename title 'Students' to 'Interns' on dashboard.
1) Go to Internmatch.
2) Log in as an Agent.
3) Confirm wording change on dashboard.
4) Log in as Edu Provider.
5) Confirm wording change on dashboard.
> Feature intm 747

- internmatch-new/pages/application/:id/offer/:university/induction/:offerId/index.json
- internmatch-new/sublayouts/home/agent/bucket.json
- internmatch-new/sublayouts/home/intern/bucket.json
- internmatch-new/sublayouts/tables/contacts/contacts.json
- internmatch-new/sublayouts/timeline/index.json
> Attr fixes

- internmatch-new/sublayouts/timeline/index.json
> changes and timeline fixes

- internmatch-new/routing.dev.json
- internmatch-new/sublayouts/home/agent/bucket.json
- internmatch-new/sublayouts/tables/companies/education-providers.json
changed attribute to be full address
> Eduprovider attr

- internmatch-new/sublayouts/home/intern/bucket.json
- internmatch-new/sublayouts/tables/companies/education-providers.json
#ChangeLog 
1. remove selct from form table in edu providers table 
2. Reorder the attributes in intern bucket in card view.
> remvoed select from table and layout reorder on bucket

- internmatch-new/pages/application/:id/inprogress/endterm/:reviewid/index.json
- internmatch-new/pages/application/:id/inprogress/midterm/:reviewid/index.json
1.  Final term review layouts.
2. Mid term bug fixes.
> Final term

- internmatch-new/sublayouts/timeline/index.json
removed route from timeline component
> Timeline fix s

- internmatch-new/pages/weekly-journals/:id/week/:weekid/index.json
Fixes while passing props to Journal
>  changed few attrs

- internmatch-new/pages/agents-table/index.json
- internmatch-new/pages/application/:id/index.json
- internmatch-new/routing.dev.json
- internmatch-new/sublayouts/application/details/index.json
- internmatch-new/sublayouts/home/agent/internship-details.json
- internmatch-new/sublayouts/home/edu-provider/index.json
- internmatch-new/sublayouts/home/hostcompany/internship-details.json
- internmatch-new/sublayouts/internship/details/index.json
- internmatch-new/sublayouts/tables/internships/active.json
- internmatch-new/sublayouts/view-intern-profile/index.json
1. added attributes 
2. changes to queries 
3. added missing attributes on profiles.
4. some of the queries don't work and data doesn't update or they take too long for that even though the query seem right.
> Attr fixe3

- internmatch-new/sublayouts/header/header.default.json
Changed a check so you can add companies and internships as a referrer.
> fixed supervisor dropdown add

- internmatch-new/sublayouts/view-details/profile/company.json
- internmatch-new/sublayouts/view-details/profile/host-company.json
passed code as a prop from company layout to host-company layout so that the item code is being passed while clicking on the button.
> edit host company

- internmatch-new/sublayouts/tables/companies/education-providers.json
> Send journal btn

- internmatch-new/sublayouts/home/agent/bucket.json
1. Fix for intern images not loading. 
2. Fix for company name not loading.
> company and image fix
